### ISSUE TITLE
Does this allow website visitors to access your Airtable API via the browser console?

### ISSUE THREAD

**Issue by jdormit** [Kallirroi/airtable_as_cms#2]
Hi! This is a really neat project - Airtable is an awesome product and it's cool to see what can be built on top of it. This isn't an issue as much as it is a question for my own education. Is the `process_api_key` exposed as a global JavaScript variable in the rendered website? 

https://github.com/Kallirroi/airtable_as_cms/blob/a523f1c75d98e07ac90b5753d603548fd15def8d/src/App.js#L8-L11

If so, does that give website visitors the ability to make API requests against your Airtable base? Or am I misunderstanding how these environment variables are being used?

**Comment by Kallirroi** [comment]
Thanks for checking it out! So the key is what authenticates the front-end's fetch request to the Airtable API, but it is not globally exposed while doing so (it lives inside the hosting platform as an environment variable). Now most platforms offer a really easy way to set these variables, screenshot from Vercel below: 

![image](https://user-images.githubusercontent.com/10440556/85149357-2ef8a980-b21f-11ea-8238-e4566f83823e.png)

Hope this helps?
